# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotation_gui.ui'
#
# Created: Fri Feb 17 19:54:12 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1547, 1052)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 900, 201, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(200, 20, 20, 981))
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 250, 201, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.groupBox_trait_visualization = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_trait_visualization.setGeometry(QtCore.QRect(440, 10, 1101, 1001))
        self.groupBox_trait_visualization.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_trait_visualization.setFlat(False)
        self.groupBox_trait_visualization.setCheckable(False)
        self.groupBox_trait_visualization.setObjectName("groupBox_trait_visualization")
        self.checkBox_visualize_lines = QtGui.QCheckBox(self.groupBox_trait_visualization)
        self.checkBox_visualize_lines.setGeometry(QtCore.QRect(400, 0, 81, 21))
        self.checkBox_visualize_lines.setChecked(True)
        self.checkBox_visualize_lines.setObjectName("checkBox_visualize_lines")
        self.checkBox_visualize_circles = QtGui.QCheckBox(self.groupBox_trait_visualization)
        self.checkBox_visualize_circles.setGeometry(QtCore.QRect(670, 0, 81, 21))
        self.checkBox_visualize_circles.setChecked(True)
        self.checkBox_visualize_circles.setObjectName("checkBox_visualize_circles")
        self.checkBox_visualize_arcs = QtGui.QCheckBox(self.groupBox_trait_visualization)
        self.checkBox_visualize_arcs.setGeometry(QtCore.QRect(760, 0, 81, 21))
        self.checkBox_visualize_arcs.setChecked(True)
        self.checkBox_visualize_arcs.setObjectName("checkBox_visualize_arcs")
        self.checkBox_visualize_rays = QtGui.QCheckBox(self.groupBox_trait_visualization)
        self.checkBox_visualize_rays.setGeometry(QtCore.QRect(580, 0, 81, 21))
        self.checkBox_visualize_rays.setChecked(True)
        self.checkBox_visualize_rays.setObjectName("checkBox_visualize_rays")
        self.checkBox_visualize_segments = QtGui.QCheckBox(self.groupBox_trait_visualization)
        self.checkBox_visualize_segments.setGeometry(QtCore.QRect(490, 0, 81, 21))
        self.checkBox_visualize_segments.setChecked(True)
        self.checkBox_visualize_segments.setObjectName("checkBox_visualize_segments")
        self.graphicsView_traits_visualization = QtGui.QGraphicsView(self.groupBox_trait_visualization)
        self.graphicsView_traits_visualization.setGeometry(QtCore.QRect(10, 30, 1081, 961))
        self.graphicsView_traits_visualization.setObjectName("graphicsView_traits_visualization")
        self.comboBox_draw_list_vs_buffer = QtGui.QComboBox(self.groupBox_trait_visualization)
        self.comboBox_draw_list_vs_buffer.setGeometry(QtCore.QRect(140, 0, 201, 24))
        self.comboBox_draw_list_vs_buffer.setObjectName("comboBox_draw_list_vs_buffer")
        self.comboBox_draw_list_vs_buffer.addItem("")
        self.comboBox_draw_list_vs_buffer.addItem("")
        self.comboBox_draw_list_vs_buffer.addItem("")
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(430, 20, 20, 981))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 90, 211, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.pushButton_reset_trait_buffer = QtGui.QPushButton(self.centralwidget)
        self.pushButton_reset_trait_buffer.setGeometry(QtCore.QRect(10, 920, 191, 27))
        self.pushButton_reset_trait_buffer.setObjectName("pushButton_reset_trait_buffer")
        self.groupBox_manual_trait_detection = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_manual_trait_detection.setGeometry(QtCore.QRect(10, 70, 191, 181))
        self.groupBox_manual_trait_detection.setObjectName("groupBox_manual_trait_detection")
        self.radioButton_man_annotate_line = QtGui.QRadioButton(self.groupBox_manual_trait_detection)
        self.radioButton_man_annotate_line.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.radioButton_man_annotate_line.setChecked(True)
        self.radioButton_man_annotate_line.setObjectName("radioButton_man_annotate_line")
        self.radioButton_man_annotate_segment = QtGui.QRadioButton(self.groupBox_manual_trait_detection)
        self.radioButton_man_annotate_segment.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.radioButton_man_annotate_segment.setObjectName("radioButton_man_annotate_segment")
        self.radioButton_man_annotate_ray = QtGui.QRadioButton(self.groupBox_manual_trait_detection)
        self.radioButton_man_annotate_ray.setGeometry(QtCore.QRect(10, 60, 171, 21))
        self.radioButton_man_annotate_ray.setObjectName("radioButton_man_annotate_ray")
        self.radioButton_man_annotate_circle = QtGui.QRadioButton(self.groupBox_manual_trait_detection)
        self.radioButton_man_annotate_circle.setGeometry(QtCore.QRect(10, 80, 171, 21))
        self.radioButton_man_annotate_circle.setToolTip("")
        self.radioButton_man_annotate_circle.setStatusTip("")
        self.radioButton_man_annotate_circle.setWhatsThis("")
        self.radioButton_man_annotate_circle.setAccessibleDescription("")
        self.radioButton_man_annotate_circle.setObjectName("radioButton_man_annotate_circle")
        self.radioButton_man_annotate_arc = QtGui.QRadioButton(self.groupBox_manual_trait_detection)
        self.radioButton_man_annotate_arc.setGeometry(QtCore.QRect(10, 100, 171, 21))
        self.radioButton_man_annotate_arc.setObjectName("radioButton_man_annotate_arc")
        self.pushButton_man_reset_trait = QtGui.QPushButton(self.groupBox_manual_trait_detection)
        self.pushButton_man_reset_trait.setGeometry(QtCore.QRect(0, 150, 181, 27))
        self.pushButton_man_reset_trait.setObjectName("pushButton_man_reset_trait")
        self.label_18 = QtGui.QLabel(self.groupBox_manual_trait_detection)
        self.label_18.setGeometry(QtCore.QRect(0, 130, 191, 16))
        self.label_18.setObjectName("label_18")
        self.pushButton_add_trait_buffer_to_list = QtGui.QPushButton(self.centralwidget)
        self.pushButton_add_trait_buffer_to_list.setGeometry(QtCore.QRect(10, 950, 191, 41))
        self.pushButton_add_trait_buffer_to_list.setObjectName("pushButton_add_trait_buffer_to_list")
        self.groupBox_trait_list_modification = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_trait_list_modification.setGeometry(QtCore.QRect(220, 110, 211, 881))
        self.groupBox_trait_list_modification.setObjectName("groupBox_trait_list_modification")
        self.pushButton_save_traits_to_file = QtGui.QPushButton(self.groupBox_trait_list_modification)
        self.pushButton_save_traits_to_file.setGeometry(QtCore.QRect(0, 850, 211, 27))
        self.pushButton_save_traits_to_file.setObjectName("pushButton_save_traits_to_file")
        self.listWidget_traits_list = QtGui.QListWidget(self.groupBox_trait_list_modification)
        self.listWidget_traits_list.setGeometry(QtCore.QRect(0, 30, 211, 751))
        self.listWidget_traits_list.setObjectName("listWidget_traits_list")
        self.pushButton_remove_selected_trait = QtGui.QPushButton(self.groupBox_trait_list_modification)
        self.pushButton_remove_selected_trait.setGeometry(QtCore.QRect(0, 820, 211, 27))
        self.pushButton_remove_selected_trait.setObjectName("pushButton_remove_selected_trait")
        self.pushButton_reset_trait_list = QtGui.QPushButton(self.groupBox_trait_list_modification)
        self.pushButton_reset_trait_list.setGeometry(QtCore.QRect(0, 790, 211, 27))
        self.pushButton_reset_trait_list.setObjectName("pushButton_reset_trait_list")
        self.groupBox_load_traits = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_load_traits.setGeometry(QtCore.QRect(220, 20, 221, 80))
        self.groupBox_load_traits.setObjectName("groupBox_load_traits")
        self.pushButton_load_traits = QtGui.QPushButton(self.groupBox_load_traits)
        self.pushButton_load_traits.setGeometry(QtCore.QRect(0, 20, 211, 27))
        self.pushButton_load_traits.setObjectName("pushButton_load_traits")
        self.radioButton_load_traits_overwrite = QtGui.QRadioButton(self.groupBox_load_traits)
        self.radioButton_load_traits_overwrite.setGeometry(QtCore.QRect(0, 50, 161, 21))
        self.radioButton_load_traits_overwrite.setChecked(True)
        self.radioButton_load_traits_overwrite.setObjectName("radioButton_load_traits_overwrite")
        self.pushButton_loading = QtGui.QPushButton(self.centralwidget)
        self.pushButton_loading.setGeometry(QtCore.QRect(10, 20, 191, 27))
        self.pushButton_loading.setObjectName("pushButton_loading")
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(0, 50, 201, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.groupBox_auto_trait_detection = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_auto_trait_detection.setGeometry(QtCore.QRect(10, 260, 211, 561))
        self.groupBox_auto_trait_detection.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_auto_trait_detection.setObjectName("groupBox_auto_trait_detection")
        self.pushButton_auto_detect_circles = QtGui.QPushButton(self.groupBox_auto_trait_detection)
        self.pushButton_auto_detect_circles.setEnabled(False)
        self.pushButton_auto_detect_circles.setGeometry(QtCore.QRect(0, 490, 191, 31))
        self.pushButton_auto_detect_circles.setObjectName("pushButton_auto_detect_circles")
        self.line_14 = QtGui.QFrame(self.groupBox_auto_trait_detection)
        self.line_14.setGeometry(QtCore.QRect(10, 470, 191, 20))
        self.line_14.setFrameShape(QtGui.QFrame.HLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtGui.QFrame(self.groupBox_auto_trait_detection)
        self.line_15.setGeometry(QtCore.QRect(10, 160, 181, 20))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtGui.QFrame(self.groupBox_auto_trait_detection)
        self.line_16.setGeometry(QtCore.QRect(10, 340, 190, 20))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.groupBox = QtGui.QGroupBox(self.groupBox_auto_trait_detection)
        self.groupBox.setGeometry(QtCore.QRect(0, 30, 201, 141))
        self.groupBox.setObjectName("groupBox")
        self.textEdit_dominant_orientations = QtGui.QTextEdit(self.groupBox)
        self.textEdit_dominant_orientations.setGeometry(QtCore.QRect(0, 94, 191, 41))
        self.textEdit_dominant_orientations.setReadOnly(False)
        self.textEdit_dominant_orientations.setObjectName("textEdit_dominant_orientations")
        self.pushButton_orientations_update_from_text = QtGui.QPushButton(self.groupBox)
        self.pushButton_orientations_update_from_text.setGeometry(QtCore.QRect(10, 44, 171, 21))
        self.pushButton_orientations_update_from_text.setObjectName("pushButton_orientations_update_from_text")
        self.pushButton_orientations_update_from_annotation = QtGui.QPushButton(self.groupBox)
        self.pushButton_orientations_update_from_annotation.setGeometry(QtCore.QRect(10, 64, 171, 21))
        self.pushButton_orientations_update_from_annotation.setObjectName("pushButton_orientations_update_from_annotation")
        self.pushButton_find_dominant_orientations = QtGui.QPushButton(self.groupBox)
        self.pushButton_find_dominant_orientations.setGeometry(QtCore.QRect(10, 20, 171, 21))
        self.pushButton_find_dominant_orientations.setObjectName("pushButton_find_dominant_orientations")
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_auto_trait_detection)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 170, 201, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.textEdit_canny_setting = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_canny_setting.setEnabled(False)
        self.textEdit_canny_setting.setGeometry(QtCore.QRect(110, 140, 71, 31))
        self.textEdit_canny_setting.setReadOnly(True)
        self.textEdit_canny_setting.setObjectName("textEdit_canny_setting")
        self.textEdit_binary_thresholding = QtGui.QTextEdit(self.groupBox_2)
        self.textEdit_binary_thresholding.setEnabled(False)
        self.textEdit_binary_thresholding.setGeometry(QtCore.QRect(110, 80, 71, 31))
        self.textEdit_binary_thresholding.setReadOnly(True)
        self.textEdit_binary_thresholding.setObjectName("textEdit_binary_thresholding")
        self.checkBox_radiography_thresholding_inverted = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_radiography_thresholding_inverted.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.checkBox_radiography_thresholding_inverted.setChecked(True)
        self.checkBox_radiography_thresholding_inverted.setObjectName("checkBox_radiography_thresholding_inverted")
        self.radioButton_radiography_source_edge = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_radiography_source_edge.setGeometry(QtCore.QRect(0, 120, 171, 20))
        self.radioButton_radiography_source_edge.setChecked(False)
        self.radioButton_radiography_source_edge.setObjectName("radioButton_radiography_source_edge")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 101, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 91, 31))
        self.label_5.setObjectName("label_5")
        self.radioButton_radiography_source_origin = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_radiography_source_origin.setGeometry(QtCore.QRect(0, 20, 191, 21))
        self.radioButton_radiography_source_origin.setChecked(True)
        self.radioButton_radiography_source_origin.setObjectName("radioButton_radiography_source_origin")
        self.radioButton_radiography_source_binary = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_radiography_source_binary.setGeometry(QtCore.QRect(0, 59, 181, 21))
        self.radioButton_radiography_source_binary.setObjectName("radioButton_radiography_source_binary")
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_auto_trait_detection)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 360, 201, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.textEdit_sinogram_peak_detection_setting = QtGui.QTextEdit(self.groupBox_3)
        self.textEdit_sinogram_peak_detection_setting.setEnabled(True)
        self.textEdit_sinogram_peak_detection_setting.setGeometry(QtCore.QRect(130, 20, 61, 31))
        self.textEdit_sinogram_peak_detection_setting.setReadOnly(False)
        self.textEdit_sinogram_peak_detection_setting.setObjectName("textEdit_sinogram_peak_detection_setting")
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(0, 20, 131, 31))
        self.label_6.setObjectName("label_6")
        self.pushButton_auto_detect_lines_radiography = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_auto_detect_lines_radiography.setGeometry(QtCore.QRect(0, 60, 191, 41))
        self.pushButton_auto_detect_lines_radiography.setObjectName("pushButton_auto_detect_lines_radiography")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1547, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_trait_visualization.setTitle(QtGui.QApplication.translate("MainWindow", "visualize traits", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visualize_lines.setText(QtGui.QApplication.translate("MainWindow", "lines", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visualize_circles.setText(QtGui.QApplication.translate("MainWindow", "circles", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visualize_arcs.setText(QtGui.QApplication.translate("MainWindow", "arcs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visualize_rays.setText(QtGui.QApplication.translate("MainWindow", "rays", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_visualize_segments.setText(QtGui.QApplication.translate("MainWindow", "segments", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_draw_list_vs_buffer.setItemText(0, QtGui.QApplication.translate("MainWindow", "draw all (buffer and list)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_draw_list_vs_buffer.setItemText(1, QtGui.QApplication.translate("MainWindow", "draw trait list", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_draw_list_vs_buffer.setItemText(2, QtGui.QApplication.translate("MainWindow", "draw trait buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reset_trait_buffer.setText(QtGui.QApplication.translate("MainWindow", "reset trait buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_manual_trait_detection.setTitle(QtGui.QApplication.translate("MainWindow", "manual trait annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_man_annotate_line.setText(QtGui.QApplication.translate("MainWindow", "line [any 2pts on the line", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_man_annotate_segment.setText(QtGui.QApplication.translate("MainWindow", "segment [1st:start, 2nd:end]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_man_annotate_ray.setText(QtGui.QApplication.translate("MainWindow", "ray [1st: start, 2nd: direction]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_man_annotate_circle.setText(QtGui.QApplication.translate("MainWindow", "circle [if 2 pts -> [center,perimeter] - if  more than 2 pts -> all on perimeter]", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_man_annotate_arc.setText(QtGui.QApplication.translate("MainWindow", "arc [at least and only 3pts; start from starting point, and end with ending point in CCW]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_man_reset_trait.setText(QtGui.QApplication.translate("MainWindow", "reset annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "[L-click: select point, R-click: wrap-up]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add_trait_buffer_to_list.setText(QtGui.QApplication.translate("MainWindow", "add trait buffer to trait list\n"
"-------->", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_trait_list_modification.setTitle(QtGui.QApplication.translate("MainWindow", "trait list modification", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save_traits_to_file.setText(QtGui.QApplication.translate("MainWindow", "save traits to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_remove_selected_trait.setText(QtGui.QApplication.translate("MainWindow", "remove selected trait", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reset_trait_list.setText(QtGui.QApplication.translate("MainWindow", "reset trait list", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_load_traits.setTitle(QtGui.QApplication.translate("MainWindow", "laod traits ", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_load_traits.setText(QtGui.QApplication.translate("MainWindow", "load traits from file (svg or yaml)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_load_traits_overwrite.setText(QtGui.QApplication.translate("MainWindow", "overwrite trait list", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_loading.setText(QtGui.QApplication.translate("MainWindow", "Load Map", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_auto_trait_detection.setTitle(QtGui.QApplication.translate("MainWindow", "auto trait detection", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_auto_detect_circles.setText(QtGui.QApplication.translate("MainWindow", "detect circles (overwrites buffer)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "dominant orientation [-90,90]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_orientations_update_from_text.setText(QtGui.QApplication.translate("MainWindow", "Manual detect: text", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_orientations_update_from_annotation.setText(QtGui.QApplication.translate("MainWindow", "Manual detect: annotation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_find_dominant_orientations.setText(QtGui.QApplication.translate("MainWindow", "Auto detection", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Source image for radiography", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_canny_setting.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">50,150,3</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_binary_thresholding.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">120,255</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_radiography_thresholding_inverted.setText(QtGui.QApplication.translate("MainWindow", "inverted", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_radiography_source_edge.setText(QtGui.QApplication.translate("MainWindow", "edge image (canny)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "thr1, thr2, apt_size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "maxVal, param2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_radiography_source_origin.setText(QtGui.QApplication.translate("MainWindow", "original image (for line maps)", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_radiography_source_binary.setText(QtGui.QApplication.translate("MainWindow", "binary image (for OGM)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "radiography and line detection", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit_sinogram_peak_detection_setting.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10,15,.15</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "sinogram peak detection\n"
"[refWin, minDist, minVal]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_auto_detect_lines_radiography.setText(QtGui.QApplication.translate("MainWindow", "detect lines with radiography\n"
"(overwrites buffer)", None, QtGui.QApplication.UnicodeUTF8))

